### ISSUE TITLE
Error with npm install raffle.js

### ISSUE THREAD

**Issue by fionnb0** [J-M1/Raffle-Notifier#2]
After copying the raffle file into a folder and running ‘npm install raffle.js’ this comes up
![440C56A3-AA00-4015-BACD-D1C9FD23A2BA](https://user-images.githubusercontent.com/64869085/81117627-4f92cb80-8f1f-11ea-8198-916122c423dc.jpeg)

**Comment by J-M1** [comment]
`npm install` not `npm install raffle.js`
